# Generated by Django 2.2.6 on 2019-12-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191220_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='section_2_description1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_2_description2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_2_description3',
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_2_description_1',
            field=models.TextField(blank=True, default='', verbose_name='Beschrijving 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_2_description_2',
            field=models.TextField(blank=True, default='', verbose_name='Beschrijving 2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_2_description_3',
            field=models.TextField(blank=True, default='', verbose_name='Beschrijving 1'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_2_subtitle1',
            field=models.CharField(default='All-in-one oplossing', max_length=64, verbose_name='Ondertitel 1'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_2_subtitle2',
            field=models.CharField(default='Ontwerpfase', max_length=64, verbose_name='Ondertitel 2'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_2_subtitle3',
            field=models.CharField(default='Realisatie', max_length=64, verbose_name='Ondertitel 3'),
        ),
    ]
