# Generated by Django 2.2.6 on 2019-12-25 20:03

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191220_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('item', models.CharField(max_length=64)),
                ('volgorde', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='design_items',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.GenericItem'),
        ),
    ]
