# Generated by Django 2.2.6 on 2019-12-27 19:52

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20191225_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericitem',
            name='volgorde',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='design_items',
        ),
        migrations.CreateModel(
            name='DesignItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='naam')),
                ('description', models.TextField(blank=True, default='', verbose_name='beschrijving')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_items', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
