# Generated by Django 2.2.6 on 2020-01-10 19:45

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_homepage_section_2_desc_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='section_2_desc_1',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Beschrijving 1'),
        ),
    ]
