# Generated by Django 2.2.6 on 2020-01-10 20:02

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200110_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='section_2_desc_2',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Beschrijving 2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_2_desc_3',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Beschrijving 3'),
        ),
    ]
