# Generated by Django 2.2.6 on 2020-01-10 20:09

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200110_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='designitem',
            name='desc',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Beschrijving'),
        ),
        migrations.AddField(
            model_name='implementationitem',
            name='desc',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Beschrijving'),
        ),
    ]
