# Generated by Django 2.2.6 on 2020-01-15 14:11

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200110_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='section_2_description_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_2_description_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_2_description_3',
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_1_desc',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Informatie'),
        ),
    ]
