# Generated by Django 2.2.6 on 2020-01-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20200115_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='section_2_extra',
            field=models.CharField(max_length=64, null=True, verbose_name='Tekst'),
        ),
    ]
