# Generated by Django 2.2.6 on 2020-01-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_homepage_section_2_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='section_3_extra',
            field=models.CharField(max_length=64, null=True, verbose_name='Tekst'),
        ),
    ]
