# Generated by Django 2.2.6 on 2020-01-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_homepage_section_3_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='section_2_extra',
            field=models.CharField(max_length=128, null=True, verbose_name='Tekst'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_3_extra',
            field=models.CharField(max_length=128, null=True, verbose_name='Tekst'),
        ),
    ]
