# Generated by Django 2.2.6 on 2020-01-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0022_auto_20200125_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='section_2_extra_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Achtergrond'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_3_extra_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Achtergrond'),
        ),
    ]
