# Generated by Django 2.2.13 on 2020-07-21 18:30

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0026_realisatie_realisatieafbeelding'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='section_2_desc_4',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Beschrijving 4'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_2_image_part_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Achtergrond 4'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_2_subtitle4',
            field=models.CharField(default='Specialisaties', max_length=64, verbose_name='Ondertitel 4'),
        ),
    ]
