# Generated by Django 2.2.13 on 2020-08-06 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0027_auto_20200721_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='section_4_extra',
            field=models.CharField(max_length=128, null=True, verbose_name='Tekst'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_4_extra_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Achtergrond'),
        ),
    ]
