# Generated by Django 2.2.13 on 2021-02-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20200806_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageformfield',
            name='clean_name',
            field=models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name'),
        ),
    ]
